#firstprogram
this is going to be the first learning towards the python lib numpy

In [1]:
import numpy as np

In [29]:
arr = np.array([1, 2, 3, 6, 4, 5]) 
rev_arr=arr[::-1]
print(rev_arr)

[5 4 6 3 2 1]


In [34]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]]) 
compare=arr1==arr2
print(compare)

[[ True  True]
 [ True  True]]


In [39]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
unique_elements, counts = np.unique(arr, return_counts=True)
most_frequent_index = np.argmax(counts)
most_frequent_value = unique_elements[most_frequent_index]
indices_of_most_frequent_value = np.where(arr == most_frequent_value)[0]
print("Most frequent value:", most_frequent_value)
print("Indices of most frequent value:", indices_of_most_frequent_value)


Most frequent value: 1
Indices of most frequent value: [0]


In [40]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
unique_elements, counts = np.unique(arr, return_counts=True)
most_frequent_index = np.argmax(counts)
most_frequent_value = unique_elements[most_frequent_index]
indices_of_most_frequent_value = np.where(arr == most_frequent_value)[0]
print("Most frequent value:", most_frequent_value)
print("Indices of most frequent value:", indices_of_most_frequent_value)


Most frequent value: 1
Indices of most frequent value: [0]


In [38]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
output=gfg.sum(axis=0)#column wise
print(output)
output2=gfg.sum(axis=1)
print(output2)

[[20  9 16]]
[[14]
 [16]
 [15]]
